source 'https://github.com/CocoaPods/Specs.git'

target 'MXTableViewController', :exclusive => true do
  pod "MXTableViewController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MXTableViewController", :path => "../"

  
end
